### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mikeatlas** [MichaelTJones/walk#2]
Hello, is there a license associated with your repository?
Thanks!

**Comment by MichaelTJones** [comment]
No…I never thought about that.

 I was just sharing openly.

Maybe I should put some sort of ultra-permissive notice there.

I was at Google for a long time and though this code was done on my own time…it was always with the spirit of helping the Go community.

Michael

**Comment by mikeatlas** [comment]
MIT is as ultra-permissive as you can get. That or WTFPL wtfpl.net

**Comment by MichaelTJones** [comment]
I just added the MIT license to the “walk” description. Some of that walk code  comes from the Go-library itself and was modified so it retains the BSD license for those parts.

Everything else is MIT-style.

**Comment by mikeatlas** [comment]
Thank you very much. Happy holidays!

**Comment by MichaelTJones** [comment]
You are most welcome. Enjoy.
